### ISSUE TITLE
Make attendance data available on a spreadsheet #116

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Ops-Programme#117]
AS A Course Lead
I WANT to know who is attending the classes
SO THAT I can identify attendance easily

**Acceptance criteria**

**Scenario: register data to be available on spreadsheet**
GIVEN register data is saved on Netlify
WHEN I go to the register spreadsheet on one of our CYF Drives
THEN I can see the date, time, name, family name and email of each person that registred.

**Comment by SallyMcGrath** [comment]
Done and handed over for review/ impl

**Comment by kfklein15** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/1YHKPCCN55PJD-o1jg4wbVKI3kbhB-ULiwB5hhG17DcA/edit

**Comment by kfklein15** [comment]
This looks great.  Thank you.
