### ISSUE TITLE
Website must inform the correct information about London distance

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Ops-Programme#131]
**Background**
Website clarity about London distance

**Acceptance criteria**
- London doesn't have the same rule of 90 minutes distance, but is 60 min within greater London (working must be validated with Sally)

**Comment by alecmccrindle** [comment]
How about this updated copy? 

I updated it on the website already but very happy to change it based on wording elsewhere: 

**Eligibility**

- Are you over 18?
- Do you live within 60 minutes of Greater London? Or, 
- Do you live within 90 minutes of: 
  - Sheffield, UK
  - Glasgow, UK
  - Manchester, UK
  - Birmingham, UK
  - Cape Town, ZA
- Are you on a low income?
- And, do you want to change your life with a career in tech?

**Comment by kfklein15** [comment]
@SallyMcGrath , are you happy with the above wording?

**Comment by SallyMcGrath** [comment]
Edited directly

**Comment by kfklein15** [comment]
@alecmccrindle , see your edited text above. Let us know if you have any further questions.

**Comment by alecmccrindle** [comment]
[Website updated](https://codeyourfuture.io/itc/) based on edit. 

Closing ticket.
