### ISSUE TITLE
Verify venue, before class 1, per course, per venue [REGION SYNC]

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Ops-Programme#150]
# Task
Validate that the venue is safe, well equipped, and suitable according to the Ops/Logistics checklist

## Checklist
https://docs.google.com/document/d/1nU0dBSXTx0h0sr0SW2YuyX754meMwfhoygD44oyrOiA/edit?usp=sharing

## What to do

Share this information with the people using the venue clearly. If a venue is not safe, well-equipped, or suitable, fix this or **cancel** class. 

## Notes

There is technically a venues spreadsheet but it's not complete and nobody is allowed to fix or share it, so inevitably volunteers will make their own versions to use at the weekend (as they always do) with the info they actually need in the moment.  Given this problem, you will need to think of a way to _find_ the information, _validate_ it, and then _make the call_ about class going ahead.

**Comment by AmyCYF** [comment]
@SallyMcGrath I have [a separate ticket](https://github.com/CodeYourFuture/Ops-Programme/issues/156) for this, currently it just reflects ITD but it will be for all the courses.
