### ISSUE TITLE
Confirm Volunteer Involvement for ITD Launch and Document Access

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#154]
**Description:**
With the ITD program launching this Friday, we need to confirm which volunteers will be involved across all participating regions. It would also be valuableto confirm each volunteer’s role and location for the launch, ensuring the information is accurate and readily accessible for reference during and after the event. This will also help streamline any last-minute communication needs.

**Acceptance Criteria:**

- [x] Volunteer Confirmation: Confirm the list of volunteers actively participating in the ITD launch, along with their assigned regions and roles (e.g., mentors, workshop facilitators, code reviewers).
- [ ] Centralised Document: Ensure this information is recorded in a central, easily accessible document

**Comment by SallyMcGrath** [comment]
Could classplanner help with this? @CodeYourFuture/class-planner bringing this use case to your attention

**Comment by AmyCYF** [comment]
@MarianaVazquezCYF are there any updates on this?

**Comment by lilianabermudes** [comment]
Mariana is using this document, Amym while Class Planner is not there yet. https://docs.google.com/spreadsheets/d/1xGDPty4h3G4UQjse2cmsS_g7WXDiJTqu5XeOQ1AG-RQ/edit?gid=906027144#gid=906027144

**Comment by MarianaVazquezCYF** [comment]
Hey yes, I had a meeting with class planner team and they will make some changes to help! 

We have almost all the teams, we will have them ready for next week! 

Question: which document are you talking about? Centralised Document: Ensure this information is recorded in a central, easily accessible document?  this is the one I am using: https://docs.google.com/spreadsheets/d/1xGDPty4h3G4UQjse2cmsS_g7WXDiJTqu5XeOQ1AG-RQ/edit?gid=148920607#gid=148920607 you will see in person and online community leaders there!
