### ISSUE TITLE
Assign Responsibility for Volunteer Communications in Preparation for ITD Launch on Friday

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#155]
**Description:**
To ensure that all committed volunteers are prepared for the ITD course starting Friday, we need to assign responsibility for pre-course communications. This includes reaching out to confirmed volunteers to provide any last-minute details, answer questions, and ensure they have access to all necessary resources. 

**Acceptance Criteria:**

- [x] Identify a team member responsible for leading communications with volunteers committed to the ITD launch.
- [x]  Outline essential pre-launch details to be communicated to volunteers, including schedules, expectations, and access to resources (e.g., Slack channels, curriculum links).
- [ ] Check-in with each volunteer by Thursday to confirm they are prepared and answer any final questions.

**Comment by MarianaVazquezCYF** [comment]
I will break this ticket per region:

- [ ] @AzinYad can do WM and NW
- [ ] @MarianaVazquezCYF will do LDN, Sheffield, Remote, Glasgow 
- [ ] @ShaunCYFSA will do South Africa

**Comment by MarianaVazquezCYF** [comment]
- Sheffield will be CJ!

**Comment by AzinYad** [comment]
I have done WM & NW completed.

**Comment by ShaunCYFSA** [comment]
I have done ZA.

**Comment by MarianaVazquezCYF** [comment]
I just need to do Glasgow!
