### ISSUE TITLE
Luma Events for Each workshop Session to Track Attendance

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#164]
**Description:**
To effectively manage attendance for each in-person session, the community team will be responsible for creating and maintaining Luma events. This will help track the expected number of attendees, manage capacity, and provide timely communication to participants. Each Luma event should include essential details.

**Acceptance Criteria:**

- [x] Event Creation by session
- [x] Attendee Information: Collect necessary attendee information during registration (e.g., name, contact details).
- [x] Communication Setup: Enable automated emails through Luma for each event to send reminders and updates to registered attendees.
- [ ] Attendance Monitoring: The Prog ops will monitor registrations and coordinate with the team if adjustments are needed based on attendance levels.

**Comment by MarianaVazquezCYF** [comment]
I think this is what we just did?

**Comment by MarianaVazquezCYF** [comment]
https://lu.ma/cbzs9ivm

**Comment by AmyCYF** [comment]
@MarianaVazquezCYF the other tickter was to define who would be responsible for the task ( it was a once off ticket). This ticket will be reused for each of the ITDs.

Please could you confirm if Luma sends automated follow-up emails to the participants reminding them about the events they have signed up to?
Could you also confirm when and how the list of participants will be shared with the volunteers? I am happy to take ownership of this task.

**Comment by AmyCYF** [comment]
Thanks @MarianaVazquezCYF will do
