### ISSUE TITLE
Clarification on Volunteer Responsibilities for Setting Up ITD Workshops on Eventbrite

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#165]
**Description**: 
We need to determine the role of volunteers in setting up Eventbrite events for our weekly ITD workshops.

**Acceptance Criteria:**
- [x] Decide if volunteers will be responsible for setting up Eventbrite events for ITD workshops.
- [ ] If yes, determine whether the Eventbrite account should be linked to a general account accessible to all volunteers or only to those setting up the events.
- [x] Determine if GDPR training is required for volunteers before they are granted access to Eventbrite data.

[How to create an event on Eventbrite for CYF instructions](https://drive.google.com/file/d/19gIRTsztNEM149USEwk61G2IsFGYvtdZ/view?usp=drive_link)

**Comment by MarianaVazquezCYF** [comment]
what do you think about this Amy? https://lu.ma/cbzs9ivm and then I would duplicate the events for the following saturdays and this would save us some logistics time!

**Comment by AmyCYF** [comment]
Yup that seems great - let's trial it for this ITD November and see how it goes.

**Comment by AmyCYF** [comment]
@MarianaVazquezCYF I made some amendments to the copy, the drop-in ticket description and updated the image.

**Comment by MarianaVazquezCYF** [comment]
Thanks Amy, I will duplicate these events in order to have 1 per each Saturday, and the first Saturday I will attach the zoom link (if you decide that we could do it remotely )
