### ISSUE TITLE
Define policies so they can be communicated

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Ops-Programme#182]
- Difference between learners/participants
- Difference between steps/sprints
- Attendance per course

**Comment by illicitonion** [comment]
I've drafted the attendance change in https://app.gitbook.com/o/-LcSabThbCRVBSHYbXg4/s/-MLT3gO-UutAs-bJiUtk/~/changes/759/~/overview (and will reflect this in the trainee agreement for the next cohort once it's approved) - I'm not sure we need to clarify any of the rest publicly.

**Comment by illicitonion** [comment]
I'm going to claim this is done - shout if you think there was more to do!

**Comment by kfklein15** [comment]
This is done. What do we need to do for this still, @illicitonion ?

**Comment by illicitonion** [comment]
I think nothing?
