### ISSUE TITLE
ITP Accredible badge

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#191]
**Description:**
Develop a badge for the Intro to Programming (ITP) course on Accredible. This badge will certify course completion and showcase the skills acquired by participants. This credential will be available to participants who meet the course requirements, providing them with a shareable badge that highlights what they have achieved.

**Acceptance Criteria:**

- [x] Description: Write a description explaining the purpose of the badge
- [x] Skills List
- [x] Badge Design
- [x] Earning Criteria: Define the requirements to earn the badge, such as attendance, completion of assignments/projects, and any final assessment criteria.

**Comment by SallyMcGrath** [comment]
Oh yes, let's set this out!
