### ISSUE TITLE
Cabinet for Aston University

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#214]
- [ ] AzinYad to purchase a locked cabinet and delivered it to Aston University. 
- [x] Ensure the cabinet is set up in the student research area arranged by Tony. 
- [x] Leave 11 laptops in the cabinet, making a total of 20 in the West Midlands, for community distribution.

**Comment by AzinYad** [comment]
I have few questions regarding this ticket @AmyCYF  & @cynthimicallef101

1. What is the budget for this purchase?and should I pay and claim the expense?
2. What size should it be?( I think we need it to hold 20 Laptops? )
3. How should I get tat into the building and the space we need it to be as it must be very heavy.
4. Who should I leave the key with? should it be Tony?

**Comment by AmyCYF** [comment]
@AzinYad Could you have a look on facebook marketplace and see if there are any cabinets on there? It doesn't need to be too big, enough to for 20 laptops and the cables. once you find something we should check with Tony Beaumont that the size is ok.

Regarding getting it into the building-  we would need to organise this with Tony.
yes the key should be with Tony

**Comment by cynthimicallef101** [comment]
Hi @AzinYad what key do you refer to? Is it the cabinet key? The best is if we have a lock with a code to close the cabinet. Then we have no problems locating the key. Thanks

**Comment by AzinYad** [comment]
@AmyCYF  I had a look sadly there is nothing can be locked at the moment, I will check again today and tomorrow but I think we need it as soon as possible before this Saturday, Am I right? in that case it might be best to have a look online, this way it will be delivered at least at Aston University, and no collection is needed(as I don't drive)

**Comment by AmyCYF** [comment]
@AzinYad I have created a post on Slack and tagged you and German in. Please could you provide some cabinet options that get delivered and liaise with G on that thread about the budget?

**Comment by cynthimicallef101** [comment]
Tony Beaumont is checking for the cabinet at Aston Uni on Tue 26.11.24.

**Comment by AzinYad** [comment]
Tony has found us a cabinet at Aston Uni room MB218b, which needs an ID card to access, he has put 9 laptops in the top right locker.
So we don't need to buy a locker anymore.
