### ISSUE TITLE
Storage Termination

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#216]
- [ ] After relocation and rubbish removal, confirm that no further storage solution is required in Birmingham, unless banners are to remain.
 - [ ] Cancel contract

**Comment by cynthimicallef101** [comment]
Safestore Birmingham unit is paid until 19th December 2024.

**Comment by AmyCYF** [comment]
Thats fine, once it is empty we can cancel the unit from the 19th Dec

**Comment by cynthimicallef101** [comment]
Birmingham Safestore unit is now closed (Closed on 03.12.2024).
