### ISSUE TITLE
Identify specific fire safety requirements and risks for each venue.

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#221]
- [ ]  Sheffield - Learn create sell
- [ ]  Manchester - DF Capital
- [ ]  Manchester - SeeSaw
- [ ]  London - Holborn Office
- [ ]  Birmingham - Aston University
- [ ]  Birmingham - iCentrum
- [ ]  Scotland - Strathclyde University

**Comment by cynthimicallef101** [comment]
@AmyCYF The fire safety requirements and risks is up to the venues themselves. The risks for each venue needs to be identified by them. We need someone qualified in fire safety to assess each venue's risk, which I am not qualified to do.
