### ISSUE TITLE
Investigate the accessibility of each venue, ensuring it meets safety and inclusion standards.

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#222]
- [ ]  Sheffield - Learn create sell
- [ ]  Manchester - DF Capital
- [ ]  Manchester - SeeSaw
- [ ]  London - Holborn Office
- [ ]  Birmingham - Aston University
- [ ]  Birmingham - iCentrum
- [ ]  Scotland - Strathclyde University

**Comment by cynthimicallef101** [comment]
This is the venue's responsibility. All we can do is review the documents. Closing the issue.
