### ISSUE TITLE
Trainee enrolment incentive

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Ops-Programme#229]
### Background

We have 16 trainees enrolled right now. We need to understand why not more people are applying

### Acceptance criteria

- Identify ITP people who have submitted 1 step
- Get volunteers to review them + send a message reminding them to sign-up as trainees
- Contact learners that have step 1 submitted and haven't yet submitted trainee enrolment to understand why
- Main focus: Sheffield, North West, West Midlands

### Owner

@kfklein15

### Stakeholder

N/a

### Approver

N/a

**Comment by kfklein15** [comment]
Sent a message to iTP trainee enrollers

**Comment by kfklein15** [comment]
@AzinYad , can I ask you to help me sending a message to the people that have not submitted any step on ITP, please? People are on this [doc](https://docs.google.com/spreadsheets/d/1AWc_jOgbcZASMvILRny0Y8pRSSVhoa_ksi52vQULZxU/edit?usp=sharing)

The message should be sent from ITP group.
Just a check-in, asking why they haven't yet submitted their step 1 of Module 1, and if they plan to do it?

If we get a reply from someone that won't continue we can archive them on the Dasboard.

**Comment by kfklein15** [comment]
Asked volunteers to approve the 4 missing Step 1.

**Comment by AzinYad** [comment]
I sent emails to all the ITP learners in the Doc you mentioned.
