### ISSUE TITLE
 Confirm Venue Availability for Saturdays in December and first week of January

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#238]
Check and confirm the availability of the following venues for Saturdays in December (14th, 21st, 28th) and the first week of January (4th):

- West Midlands: Aston University
- Scotland: Strathclyde University
- North West: DF Capital
- London: Brixton Office
- Sheffield: Learn Create Sell

Acceptance Criteria:
- [ ] Confirmation of availability for each venue on the specified dates.
- [ ] Details of any restrictions or conditions for use during December.

**Comment by cynthimicallef101** [comment]
Following venues have been contacted: 

- West Midlands: Aston University - 28th is not available. 
- Scotland: Strathclyde University
- North West: DF Capital
- Sheffield: Learn Create Sell

@AmyCYF where shall I update room availability information? In Internal Spreadsheet and Canvas? Or we collate it first, update on here and you can organise classes? Thanks

**Comment by AmyCYF** [comment]
Please add it to this ticket and share it on the All regions planning channel - Mariana and I will then communicate it to volunteers.

**Comment by cynthimicallef101** [comment]
@AmyCYF I have only heard back from Aston uni so far. As soon as I receive back, I will add it to the channel.

**Comment by cynthimicallef101** [comment]
Confirmed.
