### ISSUE TITLE
Names of volunteers that will review steps on 2nd January

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Ops-Programme#243]

**Comment by ShaunCYFSA** [comment]
Posted 2 messages in #cfy-itd and #cyf volunteers.

**Comment by ShaunCYFSA** [comment]
Morgan, Eni, Tersia, Anna Rebecca, and Ngozi have indicated that they can assist with marking.
I have scheduled two reminder messages to go off on 2 January at 8:30 am to remind volunteers (tagged volunteers).
I will add more names to the message as volunteers indicate their availability.

**Comment by kfklein15** [comment]
Thank you, Shaun. Can you tag me on the reminder too, please? :D This way I can reach out to them.
Also, can you check if all these people have access to the Dashboard. And if not, can you ask them to follow the canvas (we need them to do all the steps before giving access).

**Comment by ShaunCYFSA** [comment]
I tagged you in both messages.
Morgan, Eni, Tersia, Anna Rebecca, and Ngozi are all sorted for dashboard access to mark ITD.

**Comment by kfklein15** [comment]
This has been done. Thanks, Shaun
