### ISSUE TITLE
Create a tutorial for volunteers of the rhythm of the week!

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Ops-Programme#52]
- [ ] Make a video tutorial about how to promote and invite people to their communities
- [ ] Make a document with a checklist to guide people with the channels where they should invite people

**Comment by SallyMcGrath** [comment]
Instead of a document, how about a canvas?

**Comment by SallyMcGrath** [comment]
closing this as stale, though probably not obsolete
