### ISSUE TITLE
Review cohort planning board

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/Ops-Programme#63]
## Acceptance criteria

- [x] Extract key info from [CYF Guide - Launching a cohort](https://docs.google.com/document/d/1vwKuyAslQwWH4DOtfqa20baFili0cupor3LRES6XPgI/edit) and map to cohort planning board
- [x] Simplify/rationalise any issues as per requirements
- [x] Communicate redundancy of old docs and current progress to those doing the next check

**Comment by MarianaVazquezCYF** [comment]
I will move this to done!
