### ISSUE TITLE
Codility - Giving Cohort Feedback

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/Ops-Programme#74]
### Background

We use Codility for progressing trainee milestones but also for their learning assessment. What is the best way to provide feedback?

### Acceptance criteria

- [x] @MattCFry share example from WM5.
- [x] Discuss goals and ways of giving Codility feedback.
- [x] Determine future steps for giving Codility feedback.

### Stakeholder

@Dedekind561 @SallyMcGrath 

### Approver

@Dedekind561

**Comment by SallyMcGrath** [comment]
The trainees get their own Codility report sent to them, so it seems like this isn't needed, so long as the report is sent. 

In any case, @Dedekind561 have a think about what you want to do, if anything!

**Comment by MattCFry** [comment]
This is closed, as you said, this is not needed.

**Comment by SallyMcGrath** [comment]
That's for @Dedekind561 to decide as it's his area.
