### ISSUE TITLE
Document Trainee Tracker requirements and technical design/architecture

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Ops-Programme#84]
### Background

We discussed the Trainee tracker on the ticket [#47](https://github.com/CodeYourFuture/pd-prod-emp/issues/47).
We have tried to build the Trainee tracker 5 times already, in paid and non-paid versions, and we want to avoid having another not-usable product built.
To do so, @kfklein15 will work closely with the necessary team to ensure things don't go havoc, however, she needs @SallyMcGrath input and vision to drive it.

### Acceptance criteria

- Document requirements for Trainee Tracker
- Document technical design and architecture for the Trainee tracker
- Suggest 2 volunteers to work on this (optional)
- Suggest 1 Tech Lead to support this (optional)

### Owner
@SallyMcGrath 

### Stakeholder
@gbencci @Dedekind561 

### Approver
@kfklein15

**Comment by SallyMcGrath** [comment]
We think this might be obsolete and moved to the dashboard
