### ISSUE TITLE
Poverty Research briefing

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Ops-Programme#92]
Understanding poverty with 5 CYF personas

- define poverty, precarity, destitution
- describe resilience building and material barriers

roughly

Destitution is a permanent risk because people living in poverty have fewer resources and therefore less economic resilience to changing life events. This [lack of resilience](https://www.ons.gov.uk/peoplepopulationandcommunity/personalandhouseholdfinances/expenditure/articles/impactofincreasedcostoflivingonadultsacrossgreatbritain/julytooctober2023) is called precarity. In this briefing we will explore the experience of people living in all three bands of poverty, and how precarity constrains their opportunity to make positive change in their lives. It will also explain how Code Your Future works to increase [each person's resilience](https://www.jrf.org.uk/deep-poverty-and-destitution/what-protects-people-from-very-deep-poverty-and-what-makes-it-more) with a package of financial, social, educational, and personal support.

&c

5 personas are likely:
Carer risk of change , asylum seeker risk of destitution, single parent risk of homeless, gig worker risk of debt, long term unemployed risk of sanctions

consider applied microeconomics paper format

core resources
Poverty in the United Kingdom, A Survey of Household Resources and Standards of Living, Peter Townsend
Rowntree, esp https://www.jrf.org.uk/deep-poverty-and-destitution
IFS, esp

**Comment by SallyMcGrath** [comment]
https://docs.google.com/document/d/1haE1ppWUgoo8JsJR075D122-J6VCnXM-5OauASHiLHQ/edit?usp=sharing
